
###Добавление сотрудника
POST http://localhost:8080/employee
Content-Type: application/json

{
  "firstName": "Vasya",
  "lastName": "Ivanov",
  "department": 1,
  "salary": 2000
}
###Добавление сотрудника
POST http://localhost:8080/employee
Content-Type: application/json

{
  "firstName": "Lex",
  "lastName": "Petrov",
  "department": 1,
  "salary": 3000
}
###Добавление сотрудника
POST http://localhost:8080/employee
Content-Type: application/json

{
  "firstName": "arkadii",
  "lastName": "Pupov",
  "department": 1,
  "salary": 4000
}
###Добавление сотрудника
POST http://localhost:8080/employee
Content-Type: application/json

{
  "firstName": "Tron",
  "lastName": "",
  "department": 1,
  "salary": 5000
}
###Получение списка сотрудников
GET http://localhost:8080/employee
### Получение суммы зарплат сотрудников
GET http://localhost:8080/employee/salary/sum

### Получение сотрудника с минимальной зарплатой
GET http://localhost:8080/employee/salary/min

### Получение сотрудника с максимальной зарплатой
GET http://localhost:8080/employee/salary/max

### Получение всех сотрудников, зарплата которых больше средней зарплаты
GET http://localhost:8080/employee/high-salary